### ISSUE TITLE
Семинар 11 (Шифр Виженера)

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#10]
Работает вроде корректно, ошибок не нашел

`else (acc ++ [int_2_char (  62 + char_2_int x + mode * char_2_int (key !! ind)  )], ind+1)`
Можешь объяснить, почему там 62 стоит?)
А то строка не самая читабельная, ситуация чем-то напоминает [вот это](https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D0%B2%D0%B5%D1%82_%D0%BD%D0%B0_%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D1%8B%D0%B9_%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81_%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8,_%D0%B2%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B8_%D0%B2%D1%81%D0%B5%D0%B3%D0%BE_%D1%82%D0%B0%D0%BA%D0%BE%D0%B3%D0%BE)

В любом случае, все работает, поставлю за задание 5

**Comment by Hom4ikTop4ik** [comment]
62 = 26 + 26 + 10 (заглавные и строчные буквы латинского алфавита, а также 10 цифр)

**Comment by denisenes** [comment]
А, ну понятно
Совет для написания любых программ на любом языке -- каким-то имеющим смысл константам надо давать имена

Это как бы очевидно и просто, но все мы ленимся, поэтому надо это как привычку вводить как можно раньше

**Comment by Hom4ikTop4ik** [comment]
Понял, принял
