### ISSUE TITLE
Семинар 4 (числа Фибоначчи, периметр треугольника, lenLine, калькулятор[inc, dec, sqrt, double, /2 if>0])

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#2]
Оценка за задачки: 5
Решение 4 задачки конечно очень императивным получилось)

Что показала "глазная" отладка хвосторекурсивного фибоначчи?

**Comment by Hom4ikTop4ik** [comment]
Глпзная отладка - просто вывод всех чисел Фибоначчи, чтоб я убедился в правильности отбора чисел, кратных 5

**Comment by Hom4ikTop4ik** [comment]
Я имперотивщек, по большей части
Так и буду писать в будущем, скорее всего

**Comment by denisenes** [comment]
> Глпзная отладка - просто вывод всех чисел Фибоначчи, чтоб я убедился в правильности отбора чисел, кратных 5

Ок, а по поводу времени? Изменилось время вычислений при смене обычного Фибоначчи на хвосторекурсивного?

**Comment by denisenes** [comment]
> Я имперотивщек, по большей части
> Так и буду писать в будущем, скорее всего

Зря ты так:(
Надо же пробовать новое!

**Comment by Hom4ikTop4ik** [comment]
> > Глпзная отладка - просто вывод всех чисел Фибоначчи, чтоб я убедился в правильности отбора чисел, кратных 5
> 
> Ок, а по поводу времени? Изменилось время вычислений при смене обычного Фибоначчи на хвосторекурсивного?

Естественно, ускорилось
Нам же говорили: компилятор/интерпретатор хвостовую рекурсию превращает в цикл for (условно)

**Comment by denisenes** [comment]
Как говорится, доверяй, но проверяй. Может я или лектор вас обманули)
Или в новых версиях хаскеля что-то отломалось, кто знает...
