### ISSUE TITLE
Семинар 5 (map, множества[nub, union, intersection] и калькулятор из "Семинар 4")

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#3]
```
intersection' :: Eq a => [a] -> [a] -> [a] -- a b >>> (a ∩ b)
intersection' xs ys = foldl (\res x -> res ++ (if (elem x ys) then [x] else [])) [] xs
```
Советую быть очень осторожным с конкатенациями, особенно, если первый элемент конкатенации в среднем достаточно большой. Глянь тут описание: [тудумс](https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#v:-43--43-)

Задача 5: во-первых, много if-ов это не очень красиво, тут отлично бы вписались гарды (охранные выражения)
Во-вторых, смотрю ты прям любишь выражения в скобки обрамлять. Будущий LISP-программист походу)
![image](https://github.com/Hom4ikTop4ik/23217_MartynovBogdan/assets/55022112/7e4d7db4-f7b7-412d-8645-18fb453de022)

Почему-то 5 задача падает при таком вызове `optimizer ["inc", "dec"]`...
`optimizer'` вроде работает нормально

Оценка за задачки: 4.7, можешь поправить optimizer и получить макс балл

**Comment by Hom4ikTop4ik** [comment]
1) "optimizer" updated.
2) joke: exe.exe.exe.exe

**Comment by denisenes** [comment]
`optimizer ["sqrt", "inc", "dec", "dec", "double"]` зависает

Сложное очень решение получилось, легко багу поймать. Возможно, стоит как-то упростить

**Comment by denisenes** [comment]
Вообще, задачка про оптимизацию стоит большего количества баллов, так что наверное за этот семинар все таки 4.5 будет стоять, а то решение сейчас некорректное. А если исправишь, повышу

**Comment by Hom4ikTop4ik** [comment]
Исправил

> Вообще, задачка про оптимизацию стоит большего количества баллов, так что наверное за этот семинар все таки 4.5 будет стоять, а то решение сейчас некорректное. А если исправишь, повышу

**Comment by denisenes** [comment]
Круто, теперь и просто, и работает корректно

**Comment by denisenes** [comment]
Только пожалуйста, старайся не умещать все функцию в одну строку, сложно читать. С помощью отступов можно сделать функцию читабельнее например так
```haskell
optimizer :: [String] -> [String]
optimizer arr = y
  where
    (x:y) = reverse (foldl (\(first:acc) x ->
        if ((first, x) == ("inc", "dec")) || ((first, x) == ("dec", "inc"))
          then acc
          else x:(first:acc)
      ) [""] arr)
```

**Comment by denisenes** [comment]
Оценку повышаю до 5
