### ISSUE TITLE
Семинар 6 (разное)

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#5]
Задача 5:
Забавно, language server автоматически смог переписать твое решение транзитивности на такое
```haskell
trans :: Eq a => [a] -> BinaryRelation a -> Bool
trans a b = and [not (((x, y) `elem` b) && ((y,z) `elem` b) && notElem (x,z) b) | x<-a, y<-a, z<-a]
```
По-моему оно даже попонятнее выглядит) Анализаторы кода творят чудеса!

В остальном вроде все корректно
Оценка за задачки: 5

**Comment by Hom4ikTop4ik** [comment]
Согласен, Haskell сам по себе магия)
А анализаторы тем более
