### ISSUE TITLE
Семинар 9 (Польская нотация на стеке)

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#7]
> -- по факту, бесполезная функция

Да почему?) В instance Parsable String можно было ее использовать и не копипастить. Предлагаю даже так сделать

**Comment by denisenes** [comment]
> почти бесполезная функция (я мог не её писать, а просто вставить этот же код в instance Parsable)

Да, мог бы, действительно. Но я старался разбить задания на небольшие смысловые блоки, чтобы людям было проще их делать: в 3 задании вы занимаетесь конкретно парсингом строчек, в 4 задании упор сделан именно на реализацию своего класса типов и его инстансов

**Comment by denisenes** [comment]
В функции `func` лишний паттерн
```haskell
_ -> st
```

Все хорошо сделано, оценка за задачи -- 5

**Comment by Hom4ikTop4ik** [comment]
паттерн не лишний, а на всякий случай
я не хочу программировать в "идеальных" условиях
Я добавил этот паттерн на случай, если в стеке окажется неизвестная команда (вдруг пользователь что-то неверно ввёл)
