### ISSUE TITLE
Семинар 7-8 (Matrix)

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#8]
Снова длиннющие строки... Скоро придется заставлять переписывать :(
И еще момент: большие названия заданий это забавно, но как-то читать код сложно, лучше дальше так не делать)

В остальном все хорошо, оценка за задание -- 5

**Comment by denisenes** [comment]
А ну и вывод матриц тоже классно сделал, какой-то консольный эксель получился))

**Comment by Hom4ikTop4ik** [comment]
Постараюсь сжимать строки)
