### ISSUE TITLE
Семинар 10 (BinTree)

### ISSUE THREAD

**Issue by denisenes** [Hom4ikTop4ik/23217_MartynovBogdan#9]
**Задание 1.**
`fromList` не работает при пустом списке

`optimizedTree` -- не получилось сделать?
Не знаю, рассказывали ли вам на императивке про AVL-деревья (такая тема точно должна быть), но советую на них посмотреть, если интересно разобраться [тудумс](https://en.wikipedia.org/wiki/AVL_tree)
А есть еще такие [тудумс2](https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE-%D1%87%D1%91%D1%80%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE)
Быстрый поиск вещь весьма востребованная, так что балансировка деревьев тема достаточно широкая

**Задание 2.**
Сравнивать конструкторы данных с помощью == -- это плохой стиль. Поэтому прошу переделать на паттерн-матчинг

`repeat'` -- есть же удобная функция `replicate`)

**Задание со звездой**
`isSearchTree` не рекурсивная. Проверяет свойство только для корня, а глубже не идет.

Пока ставлю 4 за задание. Поправь ошибки)

**Comment by Hom4ikTop4ik** [comment]
про AVL-деревья рассказали неделю назад
После сессии буду делать их на Си и Haskell'е

Остальное исправил

**Comment by denisenes** [comment]
Ладно, в принципе пойдет. Задание со звездочкой, конечно, многословное получилось

Ставлю 5.5
